name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install
          uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
          with:
            args: npm install
        - name: update Chrome
          run:  sudo apt-get update && sudo apt-get install --only-upgrade google-chrome-stable
        - name: test
          run: |
            mkdir -p -m777 reports/allure-results reports/screenshots report
            npx wdio
        - name: Create reports
          if: always()
          run: |
            branch=$(git branch --show-current)
            t=$(date +"%y%m%d-%Hh%Mm%Ss")
            dest="test-results/${branch}/${t}"
            echo "Destination is: ${dest}"
            git checkout -b wip
            npm run report
            mkdir -p ${dest}
            cp -r allure-report/* ${dest}/
            git config --global user.name "githubaction"
            git config --global user.email "githubaction@githubaction.com"
            git status
            echo "Git add the test results"
            git add test-results
            echo "Git commit the test resutls"
            git commit -m "Add allure reports for branch: ${branch} at date: ${t} "
            echo "Fetach all branches"
            git fetch -a
            echo "Checkout origin/gh-pages"
            git checkout -b gh-pages origin/gh-pages
            echo "Update home results page"
            sed -i -e '/<!-- insert here -->/a\<a href=https://miladfahimi.github.io/volvo-test/test-results/'"${branch}"'/'"${t}"'>Test result for branch: '"${branch}"'    time: '"${t}"'   </a></br>' index.html
            echo "Cherry pick on top of github pages"
            git cherry-pick wip
            echo "Push the test results to github pages"
            git push origin gh-pages -u --force
            echo "View test reports here: https://miladfahimi.github.io/volvo-test/${dest}/"
